[tools]
jq = "latest"
neovim = "latest"
ghq = "latest"
act = "latest"
fzf = "latest"
ripgrep = "latest"
awscli = "latest"
lima = "latest"
colima = "latest"
gcloud = "latest"
bat = "latest"
yamlfmt = "latest"
node = "20.18.0"
go = "1.24.1"
python = "3.13.2"
terraform = "1.11.1"
starship = "latest"
java = "latest"
rust = "1"
fd = "latest"
gh = "2.68.1"
kubectl = "1.30.7"
firebase = "13.34.0"
marp-cli = "latest"
pre-commit = "latest"
uv = "0.8.14"
redis = "8.6.0"
mysql = "8.0.33"
ecspresso = "2.6.3"
ruby= "4.0.0"
"npm:neovim" = "latest"
"npm:eclint" = "latest"
"npm:typescript" = "latest"
"npm:@vercel/ncc" = "latest"
"npm:sharp-cli" = "latest"
"npm:mmcp" = "latest"
"npm:happy-coder" = "latest"
"npm:difit" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
"aqua:xxxserxxx/gotop" = "latest"

[settings]
experimental = true
